### ISSUE TITLE
Angular Material Update Clash

### ISSUE THREAD

**Issue by weilip1803** [ag-grid/ag-grid-material#1]
Bug, feature request, or proposal:
Bug

What is the expected behavior?
When updated to mat tag from the md tag, ag-grid should be displayed

What is the current behavior?
When updated to mat tag from the md tag, the ag-grid will not be displayed 

What are the steps to reproduce?
Change any Md tag to Mat tag

Which versions of Angular, Material, OS, browsers are affected?
Chrome 56, Safari 10.0.3 (untested elsewhere). Material 5.1.1

**Comment by weilip1803** [comment]
Ref -> https://github.com/ag-grid/ag-grid-angular/issues/195#issuecomment-365894089

**Comment by lunar-safari** [comment]
This is still broken. Setting height and width doesn't fix it.
